development: <%= ENV.fetch('REDIS_PORT_6379_TCP_ADDR_SESSION') %>:<%= ENV['REDIS_PORT_6379_TCP_PORT_SESSION'] || 6379 %>
test: <%= ENV.fetch('REDIS_PORT_6379_TCP_ADDR_SESSION') %>:<%= ENV['REDIS_PORT_6379_TCP_PORT_SESSION'] || 6379 %>
staging: <%= ENV.fetch('REDIS_PORT_6379_TCP_ADDR_SESSION') %>:<%= ENV['REDIS_PORT_6379_TCP_PORT_SESSION'] || 6379 %>
production: <%= ENV.fetch('REDIS_PORT_6379_TCP_ADDR_SESSION') %>:<%= ENV['REDIS_PORT_6379_TCP_PORT_SESSION'] || 6379 %>
