# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54810f3bea2529d995083cc3434ef8c3c2455819fc324610ede376885ba13dc6d1124c21e751f99e94846e490c4845eeb9be9d927afa98bf083a1e1948e8bebc

test:
  secret_key_base: adf9b338daf2a2e2a481255c5345d1f3165b75dd35433d93aab1606333d402a9a610a92718f75eb870a225098a144ce4f54631563fa0729155405a81398a9e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
